export * from "./create-storage"

export * from "./del-many"
export * from "./del"
export * from "./get-many"
export * from "./get"
export * from "./set-many"
export * from "./set"
export * from "./types"
export * from "./update"

export * from "./ext/assert"
export * from "./ext/cache"
export * from "./ext/remember"
export * from "./ext/watch"
